---

apiVersion: v1
kind: ImageStream
metadata:
  name: mule4
  labels:
    build: mule4

---

apiVersion: v1
kind: BuildConfig
metadata:
  name: mule4
  labels:
    app: mule4
    build: mule4
spec:
  strategy:
    dockerStrategy:
      type: Docker
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "rhel-minimal:7.6"
  source:
    type: Binary
  output:
    to:
      kind: ImageStreamTag
      name: "mule4:latest"
  runPolicy: Serial
  triggers: []